chmod_if_public_write: chmod_if_public_write.c
	dcc chmod_if_public_write.c -o chmod_if_public_write
print_diary: print_diary.c
	dcc print_diary.c -o print_diary
print_file_bits: print_file_bits.c
	dcc print_file_bits.c -o print_file_bits
utf8: utf8.c
	dcc utf8.c -o utf8
all: chmod_if_public_write print_diary print_file_bits utf8

.DEFAULT_GOAL := all
