q2: q2.c
	dcc q2.c -o q2

q3: q3.c
	dcc q3.c -o q3

q4: q4.c
	dcc q4.c -o q4

q5: q5.c
	dcc q5.c -o q5

q6: q6.c
	dcc q6.c -o q6

q7: q7.c
	dcc q7.c -o q7

q8: q8.c
	dcc q8.c -o q8

fib: fib.c
	dcc fib.c -o fib

all: q2 q3 q4 q5 q6 q7 q8 fib

.DEFAULT_GOAL := all

