fgrep: fgrep.c
	dcc fgrep.c -o fgrep

errors: errors.c
	dcc errors.c -o errors

first_line: first_line.c
	dcc first_line.c -o first_line

write_line: write_line.c
	dcc write_line.c -o write_line

append_line: append_line.c
	dcc append_line.c -o append_line

lseek_example: lseek_example.c
	dcc lseek_example.c -o lseek_example

all: fgrep errors first_line write_line append_line lseek_example

.DEFAULT_GOAL := all
